lang: de

crossref:
    exr-title: "Aufgabe"
    exr-prefix: "Aufgabe"

project:
  output-dir: __output

toc-depth: 1
number-depth: 1
number-sections: true
format-links: false

format: 
  revealjs:
    overview: true
    slide-number: "c/t"
    transition: fade
    transition-speed: slow
    code-line-numbers: false
    html-math-method: mathml
    theme:
      - style-slides.scss
      - style-titlepage.scss
  html:
    theme:
      - style-assignments.scss
