::: {#exr-einfeldtraeger}
## Einfeldträger mit Querschnitt

In dieser Aufgabe soll der Einfeldträger aus Abschnitt 7 um einen Querschnitt erweitert werden. Dabei sollen sowohl Rechteck- als auch I-Querschnitte verwendet werden können. Als Endergebnis soll der folgende Plot dargestellt werden.

TODO

Hinzugekommen sind die Darstellung des Querschnitts links vom System sowie die Ausgabe der maximal auftretenden Spannung.

### Klassen kopieren

Als Grundlage verwenden Sie die Dateien `RectangularSection.cs` und `ISection.cs` aus Abschnitt 5 sowie `Beam.cs` und `BeamDemo.cs` aus Abschnitt 7.

1. Kopieren Sie die Dateien in den Ordner `02-beam` des Projekts zum Abschnitt Vererbung.

1. Führen Sie die Tests in `02-beam-tests` aus, sie sollten alle grün sein.

Sie können die Klassen auch herunterladen
- [ISection](https://raw.githubusercontent.com/matthiasbaitsch/informatik-master/refs/heads/main/bausteine/05-klassen/aufgaben/projekt-musterloesung/03-section/ISection.cs){download="ISection.cs"}


### Querschnitte

