SOURCE = ../../../../software/OOTetris
TARGET = projekt

all:
	cp $(SOURCE)/OOTetris.code-workspace $(TARGET)/installation.code-workspace
	cp $(SOURCE)/.editorconfig $(TARGET)
	cp $(SOURCE)/OOTetris/*.cs $(TARGET)/01-beispielprogramm
