target-folder: c
deploy-folder: __output/aufgaben/c


# Global variable definitions
definitions:

# - bcd-bausteine-r: ${project-folder}/bausteine/bcd-bausteine-r
# - bcd-bausteine-statistik: ${project-folder}/bausteine/bcd-bausteine-statistik

- assignment-header: |
    ---
    title: "Aufgabenblatt ${sidx}"
    subtitle: "${subtitle}"
    ---

- assignment-solution-header: |
    ---
    title: "Lösungen zu Aufgabenblatt ${sidx}"
    subtitle: "${subtitle}"
    ---

# Individual jobs
jobs:

# Paket 01
- assignment-paper:
  subtitle: "Installation und erste Schritte in Visual Studio Code"
  files: 
  - ${project-folder}/paket-einleitung-und-installation/aufgaben/*.qmd
- increment-index:


# Jobs to run on the parts
jobs-on-parts:
# - copy: 
#   from: ${part-folder}/aufgaben/aufgaben.qmd
#   to: ${target-folder}/${idx}-${name}-aufgaben/${name}-aufgaben.qmd
# - copy: 
#   from: ${part-folder}/aufgaben.Rproj
#   to: ${target-folder}/${idx}-${name}-aufgaben/${name}-aufgaben.Rproj
# - copy: 
#   from: ${part-folder}/daten
#   to: ${target-folder}/${idx}-${name}-aufgaben/daten
#   optional: yes
# - copy: 
#   from: ${part-folder}/skripte
#   to: ${target-folder}/${idx}-${name}-aufgaben/skripte
#   optional: yes
# - copy: 
#   from: ${project-folder}/folien-r/quarto-template.yml
#   to: ${target-folder}/${idx}-${name}-aufgaben/_quarto.yml
# - zip:
#   zipfile: ${idx}-${name}-aufgaben.zip
#   folder: ${idx}-${name}-aufgaben
#   root: ${target-folder}
# - copy:
#   from: ${target-folder}/${idx}-${name}-aufgaben.zip
#   to: ${deploy-folder}/${idx}-${name}-aufgaben.zip
#   overwrite: yes


# Pattern to extract name from part folder
part-name-pattern: "paket\\-(.*)"

# Parts, folders relative to project root
parts:
# - folder: paket-einleitung-und-installation
