# Softwareprojekte mit Visual Studio Code und .NET

[🎥](TODO){target="_blank"} Erklärvideo auf YouTube

## Beispielhafte Projektstruktur {.smaller}

[]{.down40}

::: {.columns}
::: {.column width=38%}
```
hausarbeit-informatik/
├── hausarbeit.slnx
├── hausarbeit.code-workspace
├── .editorconfig
├── .vscode/
│   └── csharp.code-snippets
├── steel-hall/
│   ├── steel-hall.csproj
│   ├── SteelHall.cs
│   └── SteelHallDemo.cs
└── steel-hall-ui/
    ├── steel-hall-ui.csproj
    ├── MainWindow.axaml
    ├── MainWindow.axaml.cs
    ├── App.axaml
    ├── App.axaml.cs
    ├── Program.cs
    └── app.manifest
```
:::
::: {.column width=62%}
### Ordner für Programmcode

- `steel-hall/`: Berechnung und Darstellung
- `steel-hall-ui/`: Avalonia Benutzungsoberfläche
- `*.cs`: Programmcode und `*.axaml`: GUI

[]{.down20}

### Dateien für Einstellungen

- `hausarbeit.slnx`: Solution-Datei, bündelt Projekte
- `steel-hall.csproj` und `steel-hall-ui.csproj`: Projektdateien
- `hausarbeit.code-workspace` und `.vscode/`: VS-Code Einstellungen
- `.editorconfig`: Programmierkonventionen

:::
:::

[]{.down30}

- Für die Hausarbeit steht das Grundgerüst zum [Download](projekt-hausarbeit-vorlage.zip) bereit
    - Kann beliebig umbenannt werden
    - Projekte noch nicht enthalten (nächste Folie)

## Projekte anlegen und zu Solution hinzufügen {.smaller}

### Hinweise

- Die Befehle geben Sie im Terminalfenster von VS-Code ein (Menü → Terminal → New Terminal). 
- Die Folien verwenden `steel-hall`, Sie überlegen sich einen passenden Namen für Ihr eigenes Projekt

[]{.down20}

### Anlegen

```{.bash}
dotnet new console -o steel-hall
dotnet new avalonia.app -o steel-hall-ui
```

[]{.down10}

1. Projekt für die Anwendungslogik (Konsolenanwendung zum Testen)
1. Projekt für die Bedienoberfläche (Avalonia)

[]{.down10}

→ Projekte einfach wieder löschen, wenn etwas schiefgegangen ist

[]{.down20}

### Zu Solution hinzufügen

```{.bash}
dotnet sln add */*.csproj
```

[]{.down10}

1. Alle Projekte in Solution aufnehmen

[]{.down20}

Ergebnis

[]{.down10}

```{.xml filename="hausarbeit.slnx"}
{{< include projekt-hausarbeit-beispiel/hausarbeit.slnx >}}
```

## Paketmanagement mit Nuget {.smaller}

[]{.down20}

- [NuGet](https://www.nuget.org){target="_blank"}: Paketverwaltung für .NET-Bibliotheken (wie Pip für Python)
- Viele nützliche Pakete bereits verfügbar, z.B. `BoDraw.App`, `ISections`, Avalonia
- Einbinden über die Kommandozeile

    ```{.bash}
    dotnet add steel-hall/steel-hall.csproj package BoDraw.App
    dotnet add steel-hall/steel-hall.csproj package ISections
    ```

    oder mit Rechtsklick auf `steel-hall.csproj` und `Add NuGet Package...`

- Trägt jeweils eine `<PackageReference>` in die `.csproj`-Datei ein

    ```{.xml filename="steel-hall.csproj"}
    <Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        ...
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BoDraw.App" Version="1.0.44" />
        <PackageReference Include="ISections" Version="1.0.12" />
    </ItemGroup>

    </Project>
    ```

- Pakete werden beim ersten Start des Programms automatisch heruntergeladen

## Weitere Einstellungen {.smaller}

[]{.down30}

### Projektreferenz ergänzen

1. Mit rechts auf `steel-hall-ui.csproj` klicken
1. `Add Project Reference` wählen
1. Oben `steel-hall` selektieren

[]{.down10}

→ UI-Projekt verwendet Projekt mit Anwendungslogik

[]{.down30}

### Spracheinstellung (empfohlen)

```{.xml filename="steel-hall-ui.csproj" code-line-numbers="5"}
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    ...
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  ...
</Project>
```

[]{.down10}

- In Projektdatei Zeile 5 hinzufügen

[]{.down10}

→ Projekt verwendet Punkt für Dezimaltrenner (spart viel Ärger)

## Komplette Projektdatei für UI-Projekt {.smaller}

```{.xml filename="steel-hall-ui/steel-hall-ui.csproj"}
{{< include projekt-hausarbeit-beispiel/steel-hall-ui/steel-hall-ui.csproj >}}
```
